# Generated by Django 4.2.11 on 2024-03-29 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GoldCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price', models.FloatField(max_length=200)),
                ('weight', models.FloatField(max_length=200)),
                ('total_price_spend', models.FloatField(max_length=200)),
                ('total_weight_spend', models.FloatField(max_length=200)),
            ],
        ),
    ]
